DROP TABLE PAISES IF EXISTS CASCADE;
create table PAISES (
    ID_PAIS integer generated by default as identity(start with 5) primary key,
    NOMBRE varchar(100) not null,
    constraint uq_paises_nombre unique(nombre)
);
DROP TABLE DIRECCIONES IF EXISTS CASCADE;
create table DIRECCIONES (
    ID_EMPLEADO integer generated by default as identity(start with 2) primary key,
    NOMBRE_VIA varchar(100) not null,
    NUMERO_VIA varchar(10) not null,
    CODIGO_POSTAL varchar(5) not null
);
DROP TABLE EMPLEADOS IF EXISTS CASCADE;
create table EMPLEADOS (
    ID_EMPLEADO integer generated by default as identity(start with 2) primary key,
    NOMBRE varchar(100) not null,
    APELLIDO1 varchar(100) not null,
    APELLIDO2 varchar(100) not null
);

